name: Deploy to AKS via Helm

on:
  workflow_dispatch:
    inputs:
      imageTag:
        required: true
        description: "Tag of image to deploy"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      - name: AKS Context
        uses: azure/aks-set-context@v4
        with:
          resource-group: AzureGroup
          cluster-name: AKSClusterGAP

      - name: Deploy via Helm
        run: |
          helm upgrade python-web ./helm-py/python-web \
            --install \
            --namespace default \
            --set image.tag=${{ github.event.inputs.imageTag }} \
            --set image.repository="santosh.azurecr.io/python-web" \
            --atomic --wait
